name: Append to release

on:
  release:
    types:
      - "created"

jobs:
  build-kext:
    runs-on: macos-latest
    strategy:
      matrix:
        conf:
          - "Release"
          - "Debug"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - run: xcodebuild -configuration ${{ matrix.conf }}
      - name: upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ matrix.conf }}/*.zip
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
